algoritmo "soma"
var
   A ,B ,C ,D : real
inicio
       A <- ABS( 1000 - 900 )

       ESCREVAL(" RESULTADO ", A )

       B <- ABS( 890 - 800 )

       ESCREVAL(" RESULTADO ", B )

       C <- ABS( 790 - 700 )

       ESCREVAL(" RESULTADO ", C )
       
       D <- ABS( 690 - 600 )

       ESCREVAL(" RESULTADO ", D )


       ESCREVA(" O VALOR TOTAL SERIA $", -> A + B + C + D )
       




       
       
       
       
       

       
fimalgoritmo